name = "uk-retirement-planner"
main = "main.py"
compatibility_date = "2025-11-02"
compatibility_flags = ["python_workers"]

# Bind a KV Namespace. This allows your Worker to store data in a key-value store.
[[kv_namespaces]]
binding = "SCENARIOS_KV"
id = "3425d31abf8940c8b9d7b9193634960d"

[vars]
ALLOWED_ORIGINS = "*"
